---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 木叶.
--- DateTime: 2022/8/21 13:29
---


-- 参数：优惠券id，用户id
local voucherId = ARGV[1]
local userId = ARGV[2]

-- 库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 订单key
local orderKey = 'seckill:order:' .. voucherId

-- 脚本业务
-- 判断库存是否充足
local stock = tonumber(redis.call('get', stockKey))
if (stock < 1) then
    -- 库存不足，则返回1
    return 1
end
-- 判断用户是否下过单
local flag = redis.call('sismember', orderKey, userId)
if (flag == 1) then
    -- 已经下过单
    return 2
end
-- 扣减库存
redis.call('incrby', stockKey, -1)
-- 保存用户
redis.call('sadd', orderKey, userId)
return 0